# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  generate_release_info:
    runs-on: kix
    outputs:
      release_name: ${{ steps.generate_release_name.outputs.release_name }}
    steps:
      - id: generate_release_name
        run: |
          echo "release_name=$(date -u -I)" >> "$GITHUB_OUTPUT"

  build:
    needs: generate_release_info
    strategy:
        matrix:
          include:
            - boardfamily: meson64
              branch: edge
              representative: aml-s9xx-box
        fail-fast: false
    runs-on: kix
    env:
      BOARD_FAMILY: ${{ matrix.boardfamily }}
      BRANCH: ${{ matrix.branch }}
      BOARD_NAME: ${{ matrix.representative }}

    steps:
      - name: cleanup #https://github.com/actions/checkout/issues/211
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - uses: actions/checkout@v3
        with:
          repository: armbian/build
      
      - uses: actions/checkout@v3
        with:
          path: utils

      - name: Build Kernel
        run: |
          # Copy helper files.
          cp utils/* ./

          # Remove disabling DEBUG_INFO.
          sed -i 's/run_kernel_make olddefconfig/run_kernel_make KCONFIG_ALLCONFIG=.config alldefconfig/g' lib/functions/compilation/kernel-config.sh
          sed -i '/kernel_config_set_n DEBUG_INFO/d' lib/functions/compilation/armbian-kernel.sh

          # Trip modulues debug info.
          sed -i 's/run_kernel_make_long_running/run_kernel_make_long_running INSTALL_MOD_STRIP=1/g' lib/functions/compilation/kernel.sh

          # Enable BTF.
          sed -i '/CONFIG_DEBUG_INFO/d' config/kernel/linux-"$BOARD_FAMILY"-"$BRANCH".config
          echo "CONFIG_DEBUG_INFO=y
          CONFIG_DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT=y
          CONFIG_DEBUG_INFO_COMPRESSED_ZLIB=y
          CONFIG_DEBUG_INFO_BTF=y" >> config/kernel/linux-"$BOARD_FAMILY"-"$BRANCH".config

          # Compile kernel.
          ./compile.sh RELEASE=jammy JUST_KERNEL=yes KERNEL_ONLY=yes BOARD="$BOARD_NAME" BRANCH="$BRANCH" KERNEL_CONFIGURE=no

      - name: Extract vmlinux
        id: vmlinux
        run: |
          cd output/debs/
          fname=$(ls --format single-column kernel-*.tar | head -n 1)
          fpath=$(realpath ${fname})
          echo "FILE_DISPLAY_NAME=${BOARD_FAMILY}-${fname}" >> $GITHUB_OUTPUT
          echo "FILEPATH=${fpath}" >> $GITHUB_OUTPUT

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: daeuniverse/armbian-kernel-btf-dist
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          file: ${{ steps.vmlinux.outputs.FILEPATH }}
          asset_name: ${{ steps.vmlinux.outputs.FILE_DISPLAY_NAME }}
          tag: ${{ needs.generate_release_info.outputs.release_name }}
          overwrite: true
