# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
        matrix:
          include:
            - boardfamily: bcm2711
              branch: current
              representative: config/boards/rpi4b
            - boardfamily: bcm2711
              branch: edge
              representative: config/boards/rpi4b
            - boardfamily: d1
              branch: edge
              representative: config/boards/mangopi-mq
            - boardfamily: imx6
              branch: current
              representative: config/boards/cubox-i
            - boardfamily: imx6
              branch: edge
              representative: config/boards/cubox-i
            - boardfamily: imx7d
              branch: current
              representative: config/boards/imx7sabre
            - boardfamily: imx7d
              branch: legacy
              representative: config/boards/imx7sabre
            - boardfamily: media
              branch: current
              representative: config/boards/jetson-nano
            - boardfamily: media
              branch: edge
              representative: config/boards/jetson-nano
            - boardfamily: media
              branch: legacy
              representative: config/boards/khadas-edge2
            - boardfamily: meson64
              branch: current
              representative: config/boards/odroidc4
            - boardfamily: meson64
              branch: edge
              representative: config/boards/odroidc4
            - boardfamily: meson
              branch: current
              representative: config/boards/onecloud
            - boardfamily: meson
              branch: edge
              representative: config/boards/onecloud
            - boardfamily: mt7623
              branch: legacy
              representative: config/boards/bananapir2
            - boardfamily: mvebu64
              branch: current
              representative: config/boards/macchiatobin-doubleshot
            - boardfamily: mvebu64
              branch: edge
              representative: config/boards/macchiatobin-doubleshot
            - boardfamily: mvebu
              branch: current
              representative: config/boards/clearfogpro
            - boardfamily: mvebu
              branch: edge
              representative: config/boards/clearfogpro
            - boardfamily: odroidxu4
              branch: current
              representative: config/boards/odroidxu4
            - boardfamily: odroidxu4
              branch: edge
              representative: config/boards/odroidxu4
            - boardfamily: rk322x
              branch: current
              representative: config/boards/rk322x-box
            - boardfamily: rk322x
              branch: edge
              representative: config/boards/rk322x-box
            - boardfamily: rk322x
              branch: legacy
              representative: config/boards/rk322x-box
            - boardfamily: rk3399
              branch: legacy
              representative: config/boards/helios64
            - boardfamily: rk3568-odroid
              branch: edge
              representative: config/boards/odroidm1
            - boardfamily: rk35xx
              branch: legacy
              representative: config/boards/radxa-e25
            - boardfamily: rockchip64
              branch: current
              representative: config/boards/rockpro64
            - boardfamily: rockchip64
              branch: edge
              representative: config/boards/rockpro64
            - boardfamily: rockchip64
              branch: legacy
              representative: config/boards/rockpro64
            - boardfamily: rockchip
              branch: current
              representative: config/boards/tinkerboard
            - boardfamily: rockchip
              branch: edge
              representative: config/boards/tinkerboard
            - boardfamily: rockchip
              branch: legacy
              representative: config/boards/tinkerboard
            - boardfamily: rockchip-rk3588
              branch: edge
              representative: config/boards/rock-5b
            - boardfamily: rockchip-rk3588
              branch: legacy
              representative: config/boards/rock-5b
            - boardfamily: rockpis
              branch: legacy
              representative: config/boards/rockpi-s
            - boardfamily: s5p6818
              branch: legacy
              representative: config/boards/nanopifire3
            - boardfamily: starfive2
              branch: edge
              representative: config/boards/visionfive2
            - boardfamily: starfive
              branch: edge
              representative: config/boards/unleashed
            - boardfamily: sun50iw9
              branch: legacy
              representative: config/boards/orangepizero2
            - boardfamily: sunxi64
              branch: current
              representative: config/boards/lime-a64
            - boardfamily: sunxi64
              branch: edge
              representative: config/boards/lime-a64
            - boardfamily: sunxi64
              branch: legacy
              representative: config/boards/lime-a64
            - boardfamily: sunxi
              branch: current
              representative: config/boards/bananapim2plus
            - boardfamily: sunxi
              branch: edge
              representative: config/boards/bananapim2plus
            - boardfamily: sunxi
              branch: legacy
              representative: config/boards/bananapim2plus
            - boardfamily: uefi-arm64
              branch: current
              representative: config/boards/uefi-arm64
            - boardfamily: uefi-arm64
              branch: edge
              representative: config/boards/uefi-arm64
            - boardfamily: uefi-riscv64
              branch: current
              representative: config/boards/uefi-riscv64
            - boardfamily: uefi-riscv64
              branch: edge
              representative: config/boards/uefi-riscv64
            - boardfamily: uefi-x86
              branch: current
              representative: config/boards/uefi-x86
            - boardfamily: uefi-x86
              branch: edge
              representative: config/boards/uefi-x86
            - boardfamily: virtual
              branch: current
              representative: config/boards/virtual-qemu
            - boardfamily: zynq
              branch: legacy
              representative: config/boards/microzed

        fail-fast: false
    runs-on: ubuntu-latest
    env:
      BOARD_FAMILY: ${{ matrix.boardfamily }}
      BRANCH: ${{ matrix.branch }}
      BOARD_NAME: ${{ matrix.representative }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: armbian/build
      
      - uses: actions/checkout@v3
        with:
          path: utils

      - name: Build Kernel
        run: |
          # Copy helper files.
          cp utils/{merge_config.sh,.config-btf} ./

          # Remove disabling DEBUG_INFO.
          sed -i 's/run_kernel_make olddefconfig/run_kernel_make KCONFIG_ALLCONFIG=.config alldefconfig/g' lib/functions/compilation/kernel-config.sh
          sed -i '/kernel_config_set_n DEBUG_INFO/d' lib/functions/compilation/armbian-kernel.sh
          
          # Compile kernel.
          ./compile.sh RELEASE=bullseye JUST_KERNEL=yes KERNEL_ONLY=yes BOARD="$BOARD_NAME" BRANCH="$BRANCH" KERNEL_CONFIGURE=no

      - name: Extract vmlinux
        id: vmlinux
        run: |
          cd output/debs/
          fname=$(ls --format single-column linux-image-*.deb | head -n 1)
          id=$(echo $fname | cut -d- -f3-4)
          dpkg-deb -x "$fname" kernel
          filename=vmlinux_"$BOARD_FAMILY"_"$id"
          vmlinux_file_src=$(ls --format single-column kernel/boot/vmlinux* | head -n 1)
          cp "$vmlinux_file_src" "$filename"
          echo FILEPATH="$(realpath ${filename})" >> $GITHUB_OUTPUT

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.vmlinux.outputs.FILEPATH }}
